#!/usr/bin/env bash

set -euf -o pipefail

readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly CONFIG_DIR="${SCRIPT_DIR}/dotstar-emulator-${MIND_ORB_LED_MAPPING:-"HeroOrbMapping"}"

main() {
    pushd "${CONFIG_DIR}"
    pipenv run python -m DotStar_Emulator run
    popd
}

main
